<a href="https://colab.research.google.com/github/amr0ym/TM351-Data-Management-TMA/blob/main/Q1_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

# Load dataset directly from GitHub (Raw URL)
url = "https://raw.githubusercontent.com/amr0ym/TM351-Data-Management-TMA/refs/heads/main/Airline%20Dataset%20Updated%20-%20v2.csv"
df = pd.read_csv(url)

In [5]:
# Explore the structure and contents of the dataset

display(df.head())

print("Dataset Shape:")
print(df.shape)

print("Column Names:")
print(df.columns.tolist())

df.info()
display(df.describe(include="all"))

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Fransisco Hazeldine,On Time
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Marla Parsonage,On Time
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Rhonda Amber,On Time
3,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Kacie Commucci,Delayed
4,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Ebonee Tree,On Time

Dataset Shape:
(98619, 15)
Column Names:
['Passenger ID', 'First Name', 'Last Name', 'Gender', 'Age', 'Nationality', 'Airport Name', 'Airport Country Code', 'Country Name', 'Airport Continent', 'Continents', 'Departure Date', 'Arrival Airport', 'Pilot Name', 'Flight Status']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98619 entries, 0 to 98618
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Passenger ID          98619 non-null  object
 1   First Name            98619 non-null  object
 2   Last Name             98619 non-null  object
 3   Gender                98619 non-null  object
 4   Age                   98619 non-null  int64
 5   Nationality           98619 non-null  object
 6   Airport Name          98619 non-null  object
 7   Airport Country Code  98619 non-null  object
 8   Country Name          98619 non-null  object
 9   Airport Continent     98619 non-null  object
 10  Continents            98619 non-null  object
 11  Departure Date        98619 non-null  object
 12  Arrival Airport       98619 non-null  object
 13  Pilot Name            98619 non-null  object
 14  Flight Status         98619 non-null  object
dtypes: int64(1), object(14)
memory usage: 11.3+ MB

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
count,98619,98619,98619,98619,98619.000000,98619,98619,98619,98619,98619,98619,98619,98619,98619,98619
unique,98619,8437,41658,2,NaN,240,9062,235,235,6,6,364,9024,98605,3
top,8JYEcz,Gale,Dyball,Male,NaN,China,San Pedro Airport,US,United States,NAM,North America,7/22/2022,0,Byrle Schooling,Cancelled
freq,1,37,17,49598,NaN,18317,43,22104,22104,32033,32033,325,873,2,32942
mean,NaN,NaN,NaN,NaN,45.504021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,25.929849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,46.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,68.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,90.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Assess data quality: completeness and consistency

print("Missing Values:")
print(df.isnull().sum())

print("Duplicate Rows:")
print(df.duplicated().sum())

Missing Values:
Passenger ID            0
First Name              0
Last Name               0
Gender                  0
Age                     0
Nationality             0
Airport Name            0
Airport Country Code    0
Country Name            0
Airport Continent       0
Continents              0
Departure Date          0
Arrival Airport         0
Pilot Name              0
Flight Status           0
dtype: int64
Duplicate Rows:
0

In [7]:
# Identify potential data inconsistencies in categorical variables

for col in df.select_dtypes(include='object').columns:
    print(f"\nUnique values in {col}:")
    print(df[col].unique())

Unique values in Passenger ID:
['ABVWIg' 'jkXXAX' 'CdUz2g' ... 'VUPiVG' 'E47NtS' '8JYEcz']

Unique values in First Name:
['Edithe' 'Elwood' 'Darby' ... 'Merlina' 'Syd' 'Maggy']

Unique values in Last Name:
['Leggis' 'Catt' 'Felgate' ... 'Smurfitt' 'Bauldrey' 'Lucken']

Unique values in Gender:
['Female' 'Male']

Unique values in Nationality:
['Japan' 'Nicaragua' 'Russia' 'China' 'Brazil' 'Ivory Coast' 'Vietnam'
 'Palestinian Territory' 'Thailand' 'Tunisia' 'Sweden' 'Colombia' 'Greece'
 'Philippines' 'Ukraine' 'Indonesia' 'Croatia'
 'Democratic Republic of the Congo' 'France' 'Peru' 'Latvia' 'Germany'
 'Czech Republic' 'Ireland' 'Iran' 'Madagascar' 'United States' 'Ghana'
 'Mali' 'Guatemala' 'Kyrgyzstan' 'Haiti' 'Afghanistan' 'Ethiopia'
 'Tanzania' 'Nigeria' 'Cameroon' 'Morocco' 'Armenia' 'Mexico' 'Chile'
 'Albania' 'Luxembourg' 'Honduras' 'Portugal' 'Kazakhstan' 'Pakistan'
 'Poland' 'South Africa' 'Kenya' 'Serbia' 'Maldives' 'Argentina' 'Uruguay'
 'Netherlands' 'Botswana' 'Egypt' 'Syria' 'Myanmar' 'Slovenia' 'Spain'
 'Macedonia' 'Mongolia' 'Yemen' 'Benin' 'Laos' 'Norway'
 'Sao Tome and Principe' 'Venezuela' 'United Kingdom' 'Denmark'
 'Dominican Republic' 'North Korea' 'Bangladesh' 'Mozambique'
 'Bosnia and Herzegovina' 'Canada' 'Lithuania' 'Sri Lanka' 'Belarus'
 'Niger' 'Uzbekistan' 'Malaysia' 'Sierra Leone' 'Moldova' 'Switzerland'
 'Nepal' 'Belgium' 'Iraq' 'Finland' 'Uganda' 'Azerbaijan' 'East Timor'
 'Marshall Islands' 'Georgia' 'Gabon' 'New Caledonia' 'South Korea'
 'Central African Republic' 'Guinea-Bissau' 'Paraguay' 'Suriname'
 'Jamaica' 'Saint Lucia' 'Israel' 'Zambia' 'Turkmenistan' 'Burkina Faso'
 'Jordan' 'New Zealand' 'Libya' 'Mauritius' 'Somalia' 'Kiribati' 'Ecuador'
 'Namibia' 'Estonia' 'Guam' 'Costa Rica' 'Palau' 'Angola' 'Austria'
 'Tajikistan' 'Oman' 'Cyprus' 'French Guiana' 'Sudan' 'Montenegro'
 'Lebanon' 'Australia' 'Republic of the Congo' 'Cuba' 'Malta'
 'Saudi Arabia' 'Italy' 'Romania' 'Dominica' 'Bhutan' 'Western Sahara'
 'Guinea' 'Panama' 'Bolivia' 'Samoa' 'Comoros' 'Kosovo' 'Bulgaria'
 'Cambodia' 'Liechtenstein' 'Bahamas' 'Kuwait' 'Zimbabwe' 'Hungary'
 'Taiwan' 'Iceland' 'French Polynesia' 'Cape Verde' 'Lesotho'
 'Cocos Islands' 'Saint Kitts and Nevis' 'Chad' 'El Salvador' 'Bahrain'
 'Reunion' 'Christmas Island' 'Mauritania' 'Trinidad and Tobago'
 'Guadeloupe' 'Bermuda' 'Equatorial Guinea' 'Solomon Islands' 'Senegal'
 'Turkey' 'Papua New Guinea' 'Antigua and Barbuda' 'Nauru' 'Togo'
 'Slovakia' 'Guyana' 'Liberia' 'United Arab Emirates' 'Micronesia'
 'Norfolk Island' 'Qatar' 'Gambia' 'Malawi' 'Djibouti' 'Singapore'
 'Cayman Islands' 'Anguilla' 'Aruba' 'South Sudan' 'Curacao' 'Fiji'
 'Puerto Rico' 'Hong Kong' 'Faroe Islands' 'Aland Islands' 'Burundi'
 'Eritrea' 'San Marino' 'Vanuatu' 'Mayotte' 'India' 'Algeria' 'Andorra'
 'U.S. Virgin Islands' 'Belize' 'Grenada' 'Monaco' 'Seychelles' 'Jersey'
 'Barbados' 'Saint Vincent and the Grenadines' 'Martinique'
 'American Samoa' 'South Georgia and the South Sandwich Islands' 'Tuvalu'
 'Isle of Man' 'Niue' 'Saint Helena' 'Montserrat' 'Cook Islands'
 'Swaziland' 'Svalbard and Jan Mayen' 'Falkland Islands'
 'Saint Pierre and Miquelon' 'Wallis and Futuna'
 'French Southern Territories' 'Bonaire, Saint Eustatius and Saba '
 'Rwanda' 'Tokelau' 'Tonga' 'Macao' 'Saint Martin' 'Pitcairn'
 'Northern Mariana Islands' 'Greenland' 'Brunei' 'British Virgin Islands'
 'Sint Maarten']

Unique values in Airport Name:
['Coldfoot Airport' 'Kugluktuk Airport' 'Grenoble-Isère Airport' ...
 'Camaxilo Airport' 'Babelthuap Airport' 'Westchester County Airport']

Unique values in Airport Country Code:
['US' 'CA' 'FR' 'BR' 'GB' 'IT' 'MX' 'PA' 'PK' 'AU' 'ZA' 'VE' 'CN' 'MG'
 'CO' 'MR' 'MM' 'CG' 'ZM' 'WS' 'NC' 'GQ' 'PG' 'BS' 'ID' 'RU' 'BO' 'KE'
 'BF' 'GT' 'TW' 'IN' 'NO' 'CR' 'PT' 'LK' 'PF' 'MZ' 'DZ' 'NP' 'BG' 'IR'
 'HN' 'SD' 'JP' 'DO' 'IS' 'VN' 'SY' 'RO' 'KY' 'DE' 'SK' 'BW' 'SA' 'EC'
 'CM' 'MN' 'DM' 'PY' 'IL' 'HR' 'AR' 'VU' 'NZ' 'CD' 'UA' 'SE' 'NI' 'MY'
 'ET' 'PL' 'CU' 'ES' 'KH' 'OM' 'PE' 'GY' 'UY' 'MA' 'EE' 'KW' 'GR' 'SN'
 'GA' 'SO' 'CI' 'FK' 'SB' 'ZW' 'GD' 'CL' 'VI' 'MH' 'JM' 'PH' 'SR' 'PR'
 'WF' 'TN' 'TR' 'HU' 'TZ' 'SI' 'TO' 'AO' 'AF' 'LS' 'EG' 'LY' 'MW' 'CV'
 'NL' 'MO' 'LR' 'KI' 'TH' 'LA' 'MP' 'CH' 'AT' 'TG' 'AZ' 'NF' 'YE' 'JO'
 'NG' 'BZ' 'UG' 'RW' 'MV' 'KR' 'FO' 'LT' 'FM' 'FI' 'UM' 'ER' 'TL' 'FJ'
 'EH' 'DK' 'BD' 'BY' 'TM' 'MF' 'PS' 'CY' 'TV' 'CZ' 'CF' 'NR' 'AG' 'SS'
 'GL' 'DJ' 'BE' 'IQ' 'SL' 'LC' 'MT' 'TD' 'MK' 'MD' 'BA' 'UZ' 'BI' 'QA'
 'AE' 'RE' 'KZ' 'SH' 'IE' 'TC' 'KN' 'ST' 'CK' 'GN' 'SZ' 'GP' 'KG' 'BM'
 'GF' 'AS' 'HK' 'VG' 'BJ' 'HT' 'GW' 'AM' 'SV' 'GU' 'ML' 'SG' 'CC' 'GM'
 'ME' 'NE' 'BQ' 'LU' 'VC' 'KM' 'BL' 'TJ' 'SC' 'GH' 'MU' 'NU' 'BT' 'LV'
 'TT' 'AI' 'IM' 'LB' 'RS' 'GG' 'GE' 'CX' 'PM' 'YT' 'BN' 'JE' 'KP' 'GI'
 'AD' 'BH' 'BB' 'SX' 'IO' 'MQ' 'AL' 'MS' 'MC' 'AW' 'PW']

Unique values in Country Name:
['United States' 'Canada' 'France' 'Brazil' 'United Kingdom' 'Italy'
 'Mexico' 'Panama' 'Pakistan' 'Australia' 'South Africa'
 'Venezuela, Bolivarian Republic of' 'China' 'Madagascar' 'Colombia'
 'Mauritania' 'Myanmar' 'Congo' 'Zambia' 'Samoa' 'New Caledonia'
 'Equatorial Guinea' 'Papua New Guinea' 'Bahamas' 'Indonesia'
 'Russian Federation' 'Bolivia, Plurinational State of' 'Kenya'
 'Burkina Faso' 'Guatemala' 'Taiwan, Province of China' 'India' 'Norway'
 'Costa Rica' 'Portugal' 'Sri Lanka' 'French Polynesia' 'Mozambique'
 'Algeria' 'Nepal' 'Bulgaria' 'Iran, Islamic Republic of' 'Honduras'
 'Sudan' 'Japan' 'Dominican Republic' 'Iceland' 'Viet Nam'
 'Syrian Arab Republic' 'Romania' 'Cayman Islands' 'Germany' 'Slovakia'
 'Botswana' 'Saudi Arabia' 'Ecuador' 'Cameroon' 'Mongolia' 'Dominica'
 'Paraguay' 'Israel' 'Croatia' 'Argentina' 'Vanuatu' 'New Zealand'
 'Congo, The Democratic Republic of the' 'Ukraine' 'Sweden' 'Nicaragua'
 'Malaysia' 'Ethiopia' 'Poland' 'Cuba' 'Spain' 'Cambodia' 'Oman' 'Peru'
 'Guyana' 'Uruguay' 'Morocco' 'Estonia' 'Kuwait' 'Greece' 'Senegal'
 'Gabon' 'Somalia' "Côte d'Ivoire" 'Falkland Islands (Malvinas)'
 'Solomon Islands' 'Zimbabwe' 'Grenada' 'Chile' 'Virgin Islands, U.S.'
 'Marshall Islands' 'Jamaica' 'Philippines' 'Suriname' 'Puerto Rico'
 'Wallis and Futuna' 'Tunisia' 'Turkey' 'Hungary'
 'Tanzania, United Republic of' 'Slovenia' 'Tonga' 'Angola' 'Afghanistan'
 'Lesotho' 'Egypt' 'Libya' 'Malawi' 'Cabo Verde' 'Netherlands' 'Macao'
 'Liberia' 'Kiribati' 'Thailand' "Lao People's Democratic Republic"
 'Northern Mariana Islands' 'Switzerland' 'Austria' 'Togo' 'Azerbaijan'
 'Norfolk Island' 'Yemen' 'Jordan' 'Nigeria' 'Belize' 'Uganda' 'Rwanda'
 'Maldives' 'Korea, Republic of' 'Faroe Islands' 'Lithuania'
 'Micronesia, Federated States of' 'Finland'
 'United States Minor Outlying Islands' 'Eritrea' 'Timor-Leste' 'Fiji'
 'Western Sahara' 'Denmark' 'Bangladesh' 'Belarus' 'Turkmenistan'
 'Saint Martin (French part)' 'Palestine, State of' 'Cyprus' 'Tuvalu'
 'Czechia' 'Central African Republic' 'Nauru' 'Antigua and Barbuda'
 'South Sudan' 'Greenland' 'Djibouti' 'Belgium' 'Iraq' 'Sierra Leone'
 'Saint Lucia' 'Malta' 'Chad' 'North Macedonia' 'Moldova, Republic of'
 'Bosnia and Herzegovina' 'Uzbekistan' 'Burundi' 'Qatar'
 'United Arab Emirates' 'Réunion' 'Kazakhstan'
 'Saint Helena, Ascension and Tristan da Cunha' 'Ireland'
 'Turks and Caicos Islands' 'Saint Kitts and Nevis'
 'Sao Tome and Principe' 'Cook Islands' 'Guinea' 'Eswatini' 'Guadeloupe'
 'Kyrgyzstan' 'Bermuda' 'French Guiana' 'American Samoa' 'Hong Kong'
 'Virgin Islands, British' 'Benin' 'Haiti' 'Guinea-Bissau' 'Armenia'
 'El Salvador' 'Guam' 'Mali' 'Singapore' 'Cocos (Keeling) Islands'
 'Gambia' 'Montenegro' 'Niger' 'Bonaire, Sint Eustatius and Saba'
 'Luxembourg' 'Saint Vincent and the Grenadines' 'Comoros'
 'Saint Barthélemy' 'Tajikistan' 'Seychelles' 'Ghana' 'Mauritius' 'Niue'
 'Bhutan' 'Latvia' 'Trinidad and Tobago' 'Anguilla' 'Isle of Man'
 'Lebanon' 'Serbia' 'Guernsey' 'Georgia' 'Christmas Island'
 'Saint Pierre and Miquelon' 'Mayotte' 'Brunei Darussalam' 'Jersey'
 "Korea, Democratic People's Republic of" 'Gibraltar' 'Andorra' 'Bahrain'
 'Barbados' 'Sint Maarten (Dutch part)' 'British Indian Ocean Territory'
 'Martinique' 'Albania' 'Montserrat' 'Monaco' 'Aruba' 'Palau']

Unique values in Airport Continent:
['NAM' 'EU' 'SAM' 'AS' 'OC' 'AF']

Unique values in Continents:
['North America' 'Europe' 'South America' 'Asia' 'Oceania' 'Africa']

Unique values in Departure Date:
['6/28/2022' '12/26/2022' '1/18/2022' '9/16/2022' '2/25/2022' '06-10-2022'
 '10/30/2022' '04-07-2022' '8/20/2022' '04-06-2022' '5/27/2022'
 '02-06-2022' '3/19/2022' '3/24/2022' '03-07-2022' '7/18/2022' '9/23/2022'
 '3/29/2022' '11-03-2022' '09-05-2022' '2/19/2022' '11-05-2022'
 '8/24/2022' '08-06-2022' '3/20/2022' '10-03-2022' '12-05-2022'
 '04-09-2022' '4/14/2022' '7/22/2022' '08-05-2022' '3/25/2022'
 '11/23/2022' '6/25/2022' '12/21/2022' '01-11-2022' '12-11-2022'
 '12/15/2022' '6/16/2022' '07-08-2022' '5/17/2022' '2/21/2022' '3/21/2022'
 '11-08-2022' '6/22/2022' '4/26/2022' '03-06-2022' '5/13/2022' '5/15/2022'
 '12-08-2022' '9/22/2022' '02-07-2022' '7/27/2022' '11/24/2022'
 '12/18/2022' '4/29/2022' '1/31/2022' '07-05-2022' '7/20/2022'
 '11-10-2022' '07-06-2022' '10-11-2022' '5/25/2022' '10/27/2022'
 '10/25/2022' '05-02-2022' '9/14/2022' '11/25/2022' '7/15/2022'
 '8/26/2022' '02-12-2022' '5/19/2022' '7/17/2022' '11/16/2022'
 '05-07-2022' '10/29/2022' '08-09-2022' '9/26/2022' '1/20/2022'
 '08-07-2022' '12-10-2022' '9/25/2022' '11/26/2022' '04-01-2022'
 '6/17/2022' '7/31/2022' '7/14/2022' '9/17/2022' '5/18/2022' '11/28/2022'
 '4/13/2022' '06-03-2022' '7/30/2022' '04-04-2022' '01-04-2022'
 '03-08-2022' '10/26/2022' '1/13/2022' '08-01-2022' '12-04-2022'
 '3/17/2022' '2/24/2022' '8/15/2022' '10/23/2022' '4/27/2022' '5/23/2022'
 '8/19/2022' '12/28/2022' '10/28/2022' '11/15/2022' '12/24/2022'
 '10/19/2022' '10/16/2022' '10/21/2022' '04-08-2022' '12/27/2022'
 '07-12-2022' '5/31/2022' '06-11-2022' '2/17/2022' '11/30/2022'
 '7/21/2022' '2/26/2022' '08-11-2022' '6/19/2022' '8/28/2022' '12-06-2022'
 '11-01-2022' '3/30/2022' '1/23/2022' '07-11-2022' '07-03-2022'
 '4/25/2022' '8/16/2022' '10-07-2022' '11/29/2022' '3/28/2022'
 '02-08-2022' '12/17/2022' '3/26/2022' '09-01-2022' '06-07-2022'
 '08-12-2022' '1/30/2022' '8/17/2022' '10-01-2022' '2/13/2022' '5/28/2022'
 '05-12-2022' '10/13/2022' '8/23/2022' '10-05-2022' '8/21/2022'
 '05-11-2022' '03-12-2022' '7/28/2022' '11/14/2022' '09-04-2022'
 '1/14/2022' '05-05-2022' '06-12-2022' '4/18/2022' '4/24/2022' '5/29/2022'
 '09-10-2022' '6/24/2022' '09-06-2022' '04-05-2022' '01-12-2022'
 '5/21/2022' '1/25/2022' '07-07-2022' '02-02-2022' '1/26/2022'
 '05-03-2022' '9/24/2022' '8/27/2022' '1/27/2022' '07-09-2022' '6/20/2022'
 '10-08-2022' '10-12-2022' '12/16/2022' '2/18/2022' '5/30/2022'
 '6/26/2022' '2/20/2022' '10/22/2022' '10/14/2022' '02-03-2022'
 '6/15/2022' '12-09-2022' '01-02-2022' '10/31/2022' '06-09-2022'
 '06-02-2022' '6/23/2022' '12/19/2022' '9/29/2022' '11/27/2022'
 '8/30/2022' '12-03-2022' '1/16/2022' '11/20/2022' '11-11-2022'
 '12/13/2022' '10/20/2022' '12/22/2022' '4/21/2022' '3/14/2022'
 '9/20/2022' '1/17/2022' '03-05-2022' '6/21/2022' '12/30/2022' '4/16/2022'
 '4/30/2022' '02-05-2022' '8/14/2022' '03-04-2022' '09-07-2022'
 '12/23/2022' '9/28/2022' '04-12-2022' '7/16/2022' '09-02-2022'
 '07-10-2022' '03-03-2022' '10/17/2022' '8/13/2022' '03-09-2022'
 '2/27/2022' '1/28/2022' '08-03-2022' '03-01-2022' '9/18/2022'
 '10/24/2022' '6/18/2022' '08-10-2022' '02-04-2022' '10-09-2022'
 '05-08-2022' '5/26/2022' '11-02-2022' '12-12-2022' '3/23/2022'
 '09-03-2022' '6/13/2022' '06-04-2022' '9/15/2022' '04-10-2022'
 '1/22/2022' '6/14/2022' '08-08-2022' '9/13/2022' '2/14/2022' '10/18/2022'
 '02-11-2022' '1/19/2022' '4/22/2022' '10-10-2022' '09-12-2022'
 '01-10-2022' '9/21/2022' '1/15/2022' '12/20/2022' '12-07-2022'
 '2/15/2022' '9/30/2022' '01-08-2022' '4/20/2022' '04-11-2022'
 '01-09-2022' '6/29/2022' '8/22/2022' '8/18/2022' '4/28/2022' '07-02-2022'
 '06-01-2022' '05-09-2022' '8/29/2022' '7/25/2022' '5/20/2022' '5/16/2022'
 '2/28/2022' '7/13/2022' '01-07-2022' '03-11-2022' '3/27/2022'
 '09-08-2022' '06-05-2022' '9/19/2022' '4/15/2022' '7/29/2022'
 '12/25/2022' '2/16/2022' '11/21/2022' '01-03-2022' '01-01-2022'
 '07-01-2022' '2/22/2022' '9/27/2022' '04-03-2022' '7/23/2022'
 '11-04-2022' '09-09-2022' '11/22/2022' '4/17/2022' '09-11-2022'
 '10-06-2022' '11/18/2022' '08-02-2022' '11-12-2022' '3/18/2022'
 '11/17/2022' '4/19/2022' '1/24/2022' '02-09-2022' '05-01-2022'
 '10/15/2022' '02-01-2022' '12-01-2022' '7/19/2022' '5/14/2022'
 '1/29/2022' '08-04-2022' '05-10-2022' '11-09-2022' '3/16/2022'
 '6/30/2022' '05-04-2022' '01-05-2022' '11-06-2022' '5/22/2022'
 '8/25/2022' '11/13/2022' '05-06-2022' '10-02-2022' '11/19/2022'
 '12-02-2022' '8/31/2022' '2/23/2022' '3/15/2022' '10-04-2022'
 '01-06-2022' '11-07-2022' '06-06-2022' '7/24/2022' '3/13/2022'
 '4/23/2022' '06-08-2022' '07-04-2022' '3/31/2022' '5/24/2022' '1/21/2022'
 '12/29/2022' '03-02-2022' '6/27/2022' '3/22/2022' '7/26/2022'
 '12/14/2022' '04-02-2022' '02-10-2022' '03-10-2022']

Unique values in Arrival Airport:
['CXF' 'YCO' 'GNB' ... 'CXM' 'ROR' 'HPN']

Unique values in Pilot Name:
['Fransisco Hazeldine' 'Marla Parsonage' 'Rhonda Amber' ... 'Gearalt Main'
 'Judon Chasle' 'Auguste Tindley']

Unique values in Flight Status:
['On Time' 'Delayed' 'Cancelled']